---

- include_tasks: prepare.yml

- name: install
  package:
    name: "{{ fail2ban_packages }}"
    state: present
  tags:
    - configuration
    - fail2ban
    - fail2ban-install

- include_tasks: configure.yml

- name: start and enable service
  service:
    name: fail2ban
    state: started
    enabled: true
  tags:
    - configuration
    - fail2ban
    - fail2ban-start-enable-service
