---

- name: prepare
  ansible.builtin.include_tasks: prepare.yaml
  tags:
    - fail2ban_prepare
    - fail2ban_configure

- name: install
  ansible.builtin.include_tasks: install.yaml
  tags:
    - fail2ban_install

- name: configure
  ansible.builtin.include_tasks: configure.yaml
  tags:
    - fail2ban_configure

- name: service
  ansible.builtin.include_tasks: service.yaml
  tags:
    - fail2ban_service

...
