---

- name: merge fail2ban_jails configuration between defaults and custom
  set_fact:
    fail2ban_jails: "{{ fail2ban_jails_defaults | merge_jails( fail2ban_jails ) }}"

- name: merge fail2ban_conf configuration between defaults and custom
  set_fact:
    fail2ban_conf: "{{ fail2ban_conf_default | combine( fail2ban_conf, recursive=True ) }}"

- name: merge fail2ban_jail configuration between defaults and custom
  set_fact:
    fail2ban_jail: "{{ fail2ban_jail_default | combine( fail2ban_jail, recursive=True ) }}"
